name: nks
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0" # Ensure compatibility with your Flutter SDK version.

dependencies:
  flutter:
    sdk: flutter

  # Adds video player package to handle video files in Flutter.
  video_player: any

  # Cupertino icons for iOS-style icons.
  cupertino_icons: ^1.0.8
  google_fonts: any
  gif: ^2.3.0
  page_transition: ^2.1.0
  carousel_slider: any
  action_slider: ^0.7.0
  smooth_page_indicator: ^1.2.0+3
  awesome_bottom_bar: ^1.2.4
  salomon_bottom_bar: ^3.3.0
  palette_generator: ^0.3.0
  shimmer: any
  animated_text_kit: ^4.2.2
  provider: ^6.1.2
  stylish_bottom_bar: ^1.1.0
  dotted_line: any
  shared_preferences: ^2.0.11
  firebase_storage: ^12.3.6




  # Testing
  firebase_crashlytics: ^4.2.0
  slider_button: ^2.1.0
  velocity_x: ^4.2.1
  wx_text: ^3.0.0
  url_launcher: any
  multi_select_flutter: ^4.0.0
  blurrycontainer: any
  flutter_staggered_grid_view: ^0.7.0
  skeletonizer: ^1.4.2
  flutter_snake_navigationbar: ^0.6.1
  blurbox: ^0.0.4
  image_picker: ^1.1.2




  # Google and Firebase Dependencies
  firebase_core: any
  firebase_auth: any
  firebase_messaging: any
  google_sign_in: any
  email_validator: any
  cloud_firestore: any
  lottie: ^3.1.3
  razorpay_flutter: ^1.3.0
  flutter_pay_upi: ^0.2.1
  searchbar_animation: ^0.0.4
  super_cupertino_navigation_bar: ^2.1.2
  flutter_spinkit: ^5.2.1
  firebase_analytics: ^11.3.6
  animated_digit: ^3.2.3
  geolocator: ^13.0.2
  cached_network_image: ^3.4.1
  auto_size_text: ^3.0.0
  intl: ^0.19.0
  step_progress_indicator: ^1.0.2
  swipeable_button_view: ^0.0.2
  flutter_timezone: ^4.0.0




dev_dependencies:
  flutter_launcher_icons: ^0.14.1  # Replace with the latest version from pub.dev

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"  # Path to your custom app icon

  flutter_test:
    sdk: flutter

  # Recommended linting rules for better coding practices.
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Including the video file for the splash screen.
  assets:
    - assets/videos/
    - assets/images/

  # You can add other assets like images, fonts, etc., in this section.
  # Example:
  # - assets/images/...

  # To add custom fonts, you can uncomment and modify this section:
  fonts:
    - family: Bonelloo
      fonts:
          - asset: assets/fonts/bonelloo.otf
    - family: Math
      fonts:
        - asset: assets/fonts/Mathreal.otf
    - family: Bonello
      fonts:
        - asset: assets/fonts/bonello.otf
    - family: Marline
      fonts:
        - asset: assets/fonts/Marline.otf
    - family: Inter
      fonts:
        - asset: assets/fonts/bold.ttf
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
    - family: Barette
      fonts:
        - asset: assets/fonts/barette.ttf
    - family: Vivid
      fonts:
        - asset: assets/fonts/Vividly-Regular.ttf
    - family: Renatha
      fonts:
        - asset: assets/fonts/RenathaSignature.otf
    - family: Baby
      fonts:
        - asset: assets/fonts/Baby Doll.ttf
